In [1]:
import requests
from bs4 import BeautifulSoup as bs
from urllib import request
import pandas as pd
import numpy as np

In [2]:
data = requests.get('https://www.kpetro.or.kr/lay1/S1T602C603/contents.do')
soup = bs(data.text, 'html.parser')
a = soup.select('#subContent > section > div > table > tbody')

list_a = [a[i].text for i in np.arange(len(a))]
list_a = list_a[0].split( )

In [3]:
a = list_a[1:7]
b = list_a[8:14]
c = list_a[15:21]
d = list_a[22:28]
e = list_a[29:35]
f = list_a[36:42]
g = list_a[43:49]
h = list_a[50:56]
i = list_a[57:63]
j = list_a[64:70]
k = list_a[71:77]
l = list_a[78:84]
m = list_a[85:91]
n = list_a[92:98]
o = list_a[99:105]
p = list_a[106:112]
q = list_a[113:119]
r = list_a[120:126]

In [4]:
df = pd.DataFrame(columns=['강원도','경기도','경상남도','경상북도','광주광역시','대구광역시','대전광역시','부산광역시','서울특별시','세종특별자치시','울산광역시','인천광역시','전라남도','전라북도','제주도','충청남도','충청북도','계'])
df['강원도'] = a
df['경기도'] = b
df['경상남도'] = c
df['경상북도'] = d
df['광주광역시'] = e
df['대구광역시'] = f
df['대전광역시'] = g
df['부산광역시'] = h
df['서울특별시'] = i
df['세종특별자치시'] = j
df['울산광역시'] = k
df['인천광역시'] = l
df['전라남도'] = m
df['전라북도'] = n
df['제주도'] = o
df['충청남도'] = p
df['충청북도'] = q
df['계'] = r

ValueError: 18 columns passed, passed data had 6 columns

In [ ]:
df = df.T
df.columns =[2017,2018,2019,2020,2021,2022]
df

           2017    2018    2019    2020    2021    2022
강원도         708     681     674     675     659     644
경기도       2,426   2,386   2,396   2,391   2,361   2,338
경상남도      1,166   1,150   1,135   1,117   1,090   1,075
경상북도      1,314   1,278   1,287   1,263   1,264   1,245
광주광역시       288     280     277     269     262     261
대구광역시       374     369     364     348     343     331
대전광역시       251     240     240     236     227     220
부산광역시       433     427     416     403     387     382
서울특별시       537     508     496     488     470     446
세종특별자치시      64      64      66      68      69      67
울산광역시       250     244     239     240     237     234
인천광역시       349     346     342     336     330     325
전라남도        926     904     902     899     877     866
전라북도        918     906     903     902     883     854
제주도         193     193     194     194     194     195
충청남도      1,055   1,034   1,033   1,026   1,008   1,004
충청북도        755     740     736     734     717     710
계        12,007  11,750  11,700  11,589  11,378  11,197

In [ ]:
df.to_csv('석유판매업소 현황 지역별 2017-2022.9.csv')